### ISSUE TITLE
Update python version in wiki

### ISSUE THREAD

**Issue by fredjaya** [cogent3/c3dev#35]
In [Installing Cogent3 for development](https://github.com/cogent3/c3dev/wiki/Installing-Cogent3-for-development) example code chunks use 3.8 (e.g. `nox -s test-3.8`), but the conda environment uses by default 3.10. Either replace all with 3.10 or placeholder `<python-version>`.

**Comment by GavinHuttley** [comment]
Great idea! please use <python-version>
