### ISSUE TITLE
Checking git hooks

### ISSUE THREAD

**Issue by fredjaya** [cogent3/c3dev#38]
**Pre-commit hooks**
Currently, the pre-commit script will print a success message regardless if black/isort fails.
- Add black and isort to `c3dev_environment.yml`
- Add a catch for black or isort fails in the pre-commit sample

Related to #23

**Pre-push hooks**
Currently, _all_ test sessions are run (see: [output](https://github.com/cogent3/cogent3/issues/1466#issuecomment-1745891175)) and pushing to origin fails. 
- Add instructions in wiki to avoid running all tests `nox` to one session `nox -s test-3.10` in pre-push hook

**Comment by fredjaya** [comment]
@GavinHuttley is it ok to include `black` and `isort` as part of the c3dev conda environment, or better to install via e.g. pip until #23 is implemented?

`nox` as well? #36

**Comment by GavinHuttley** [comment]
All of these tools are specified in the `pyproject.toml`. I am going to delete all conda environment files.

We should be instructing users how to make a "blank" conda environment, or python virtual environment, for the correct python version and do a "developer install" using `flit` from their cloned repository.

Closing this issue, leaving the pre-commit hook for possibly a derivative of #23
