### ISSUE TITLE
Remove mercurical commands page

### ISSUE THREAD

**Issue by fredjaya** [cogent3/c3dev#40]
[Mercurial how-to](https://github.com/cogent3/c3dev/wiki/Useful-mercurial-commands) and [https://github.com/cogent3/c3dev/wiki/Configuring-Mercurial](https://github.com/cogent3/c3dev/wiki/Configuring-Mercurial) pages not needed, new contributors to use git.

**Comment by GavinHuttley** [comment]
Correct 😢
