### ISSUE TITLE
Restructure wiki home page

### ISSUE THREAD

**Issue by fredjaya** [cogent3/c3dev#41]
Rewrite and restructure the [wiki home page](https://github.com/cogent3/c3dev/wiki) as a succinct [how-to guide](https://diataxis.fr/how-to-guides/#how-to). 

Move reference material, such as style guides, to a separate dedicated page.

Use dropdowns #37

**Comment by GavinHuttley** [comment]
reference material should be structured into individual pages, since some of that material could be quite verbose.

**Comment by fredjaya** [comment]
Happening naturally as more content is added
