### ISSUE TITLE
Recommended way of updating forked origin with remote?

### ISSUE THREAD

**Issue by fredjaya** [cogent3/c3dev#42]
Should contributors adhere strictly to either `merge` or `rebase` before PRs?

Are there any other git-specific things to consider? i.e. https://numpy.org/doc/stable/dev/development_workflow.html#additional-things-you-might-want-to-do

**Comment by fredjaya** [comment]
Related to the [[Cautionary notes for development]](https://github.com/cogent3/c3dev/wiki/Cautionary-notes-for-development) point, where your fork should always by up-to-date  with upstream

**Comment by GavinHuttley** [comment]
Good questions.

Here's my thinking. When a contributor makes a PR, a core dev has to review it. We only want to see the changes that they have made relative to the issue they're tackling.

My general advice is they create a new branch for each issue they work on (and keep those branches, and thus issues, separate). They should then try and keep their fork up-to-date using the GitHub sync with upstream feature and rebase their branch with cogent3@develop.

When they do their PR, they should do it to the cogent3@develop branch. I'd chat about this with @khiron and @KatherineCaley  during the next meeting. Both have experienced different strategies.

**Comment by fredjaya** [comment]
Consensus is to rebase.

**Comment by fredjaya** [comment]
Added to https://github.com/cogent3/c3dev/wiki/Development-practices-for-cogent3#keeping-your-feature-branch-updated
